#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="qlbb")]
	public partial class Data_qlbbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertBienBan(BienBan instance);
    partial void UpdateBienBan(BienBan instance);
    partial void DeleteBienBan(BienBan instance);
    #endregion
		
		public Data_qlbbDataContext() : 
				base(global::DAL.Properties.Settings.Default.qlbbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Data_qlbbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Data_qlbbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Data_qlbbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Data_qlbbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<BienBan> BienBans
		{
			get
			{
				return this.GetTable<BienBan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTaiKhoan;
		
		private string _tenTaiKhoan;
		
		private string _matKhau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTaiKhoanChanging(int value);
    partial void OnidTaiKhoanChanged();
    partial void OntenTaiKhoanChanging(string value);
    partial void OntenTaiKhoanChanged();
    partial void OnmatKhauChanging(string value);
    partial void OnmatKhauChanged();
    #endregion
		
		public TaiKhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTaiKhoan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTaiKhoan
		{
			get
			{
				return this._idTaiKhoan;
			}
			set
			{
				if ((this._idTaiKhoan != value))
				{
					this.OnidTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._idTaiKhoan = value;
					this.SendPropertyChanged("idTaiKhoan");
					this.OnidTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenTaiKhoan", DbType="VarChar(50)")]
		public string tenTaiKhoan
		{
			get
			{
				return this._tenTaiKhoan;
			}
			set
			{
				if ((this._tenTaiKhoan != value))
				{
					this.OntenTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._tenTaiKhoan = value;
					this.SendPropertyChanged("tenTaiKhoan");
					this.OntenTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="VarChar(50)")]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this.OnmatKhauChanging(value);
					this.SendPropertyChanging();
					this._matKhau = value;
					this.SendPropertyChanged("matKhau");
					this.OnmatKhauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BienBan")]
	public partial class BienBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idBienBan;
		
		private string _tieuDe;
		
		private System.Nullable<System.DateTime> _thoiGian;
		
		private string _noiDung;
		
		private string _khoa;
		
		private string _thanhPhanThamGia;
		
		private string _thongTinNguoiDu;
		
		private string _thuKi;
		
		private string _chuTri;
		
		private string _ketLuan;
		
		private string _yKien;
		
		private System.Nullable<System.DateTime> _thoiGianBatDau;
		
		private string _diaDiem;
		
		private System.Nullable<System.DateTime> _thoiGianKetThuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidBienBanChanging(int value);
    partial void OnidBienBanChanged();
    partial void OntieuDeChanging(string value);
    partial void OntieuDeChanged();
    partial void OnthoiGianChanging(System.Nullable<System.DateTime> value);
    partial void OnthoiGianChanged();
    partial void OnnoiDungChanging(string value);
    partial void OnnoiDungChanged();
    partial void OnkhoaChanging(string value);
    partial void OnkhoaChanged();
    partial void OnthanhPhanThamGiaChanging(string value);
    partial void OnthanhPhanThamGiaChanged();
    partial void OnthongTinNguoiDuChanging(string value);
    partial void OnthongTinNguoiDuChanged();
    partial void OnthuKiChanging(string value);
    partial void OnthuKiChanged();
    partial void OnchuTriChanging(string value);
    partial void OnchuTriChanged();
    partial void OnketLuanChanging(string value);
    partial void OnketLuanChanged();
    partial void OnyKienChanging(string value);
    partial void OnyKienChanged();
    partial void OnthoiGianBatDauChanging(System.Nullable<System.DateTime> value);
    partial void OnthoiGianBatDauChanged();
    partial void OndiaDiemChanging(string value);
    partial void OndiaDiemChanged();
    partial void OnthoiGianKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnthoiGianKetThucChanged();
    #endregion
		
		public BienBan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBienBan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idBienBan
		{
			get
			{
				return this._idBienBan;
			}
			set
			{
				if ((this._idBienBan != value))
				{
					this.OnidBienBanChanging(value);
					this.SendPropertyChanging();
					this._idBienBan = value;
					this.SendPropertyChanged("idBienBan");
					this.OnidBienBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieuDe", DbType="NVarChar(100)")]
		public string tieuDe
		{
			get
			{
				return this._tieuDe;
			}
			set
			{
				if ((this._tieuDe != value))
				{
					this.OntieuDeChanging(value);
					this.SendPropertyChanging();
					this._tieuDe = value;
					this.SendPropertyChanged("tieuDe");
					this.OntieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiGian", DbType="Date")]
		public System.Nullable<System.DateTime> thoiGian
		{
			get
			{
				return this._thoiGian;
			}
			set
			{
				if ((this._thoiGian != value))
				{
					this.OnthoiGianChanging(value);
					this.SendPropertyChanging();
					this._thoiGian = value;
					this.SendPropertyChanged("thoiGian");
					this.OnthoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiDung", DbType="NVarChar(MAX)")]
		public string noiDung
		{
			get
			{
				return this._noiDung;
			}
			set
			{
				if ((this._noiDung != value))
				{
					this.OnnoiDungChanging(value);
					this.SendPropertyChanging();
					this._noiDung = value;
					this.SendPropertyChanged("noiDung");
					this.OnnoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoa", DbType="NVarChar(50)")]
		public string khoa
		{
			get
			{
				return this._khoa;
			}
			set
			{
				if ((this._khoa != value))
				{
					this.OnkhoaChanging(value);
					this.SendPropertyChanging();
					this._khoa = value;
					this.SendPropertyChanged("khoa");
					this.OnkhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhPhanThamGia", DbType="NVarChar(4000)")]
		public string thanhPhanThamGia
		{
			get
			{
				return this._thanhPhanThamGia;
			}
			set
			{
				if ((this._thanhPhanThamGia != value))
				{
					this.OnthanhPhanThamGiaChanging(value);
					this.SendPropertyChanging();
					this._thanhPhanThamGia = value;
					this.SendPropertyChanged("thanhPhanThamGia");
					this.OnthanhPhanThamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thongTinNguoiDu", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string thongTinNguoiDu
		{
			get
			{
				return this._thongTinNguoiDu;
			}
			set
			{
				if ((this._thongTinNguoiDu != value))
				{
					this.OnthongTinNguoiDuChanging(value);
					this.SendPropertyChanging();
					this._thongTinNguoiDu = value;
					this.SendPropertyChanged("thongTinNguoiDu");
					this.OnthongTinNguoiDuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thuKi", DbType="NVarChar(100)")]
		public string thuKi
		{
			get
			{
				return this._thuKi;
			}
			set
			{
				if ((this._thuKi != value))
				{
					this.OnthuKiChanging(value);
					this.SendPropertyChanging();
					this._thuKi = value;
					this.SendPropertyChanged("thuKi");
					this.OnthuKiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuTri", DbType="NVarChar(100)")]
		public string chuTri
		{
			get
			{
				return this._chuTri;
			}
			set
			{
				if ((this._chuTri != value))
				{
					this.OnchuTriChanging(value);
					this.SendPropertyChanging();
					this._chuTri = value;
					this.SendPropertyChanged("chuTri");
					this.OnchuTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ketLuan", DbType="NVarChar(MAX)")]
		public string ketLuan
		{
			get
			{
				return this._ketLuan;
			}
			set
			{
				if ((this._ketLuan != value))
				{
					this.OnketLuanChanging(value);
					this.SendPropertyChanging();
					this._ketLuan = value;
					this.SendPropertyChanged("ketLuan");
					this.OnketLuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yKien", DbType="NVarChar(MAX)")]
		public string yKien
		{
			get
			{
				return this._yKien;
			}
			set
			{
				if ((this._yKien != value))
				{
					this.OnyKienChanging(value);
					this.SendPropertyChanging();
					this._yKien = value;
					this.SendPropertyChanged("yKien");
					this.OnyKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiGianBatDau", DbType="DateTime")]
		public System.Nullable<System.DateTime> thoiGianBatDau
		{
			get
			{
				return this._thoiGianBatDau;
			}
			set
			{
				if ((this._thoiGianBatDau != value))
				{
					this.OnthoiGianBatDauChanging(value);
					this.SendPropertyChanging();
					this._thoiGianBatDau = value;
					this.SendPropertyChanged("thoiGianBatDau");
					this.OnthoiGianBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaDiem", DbType="NVarChar(500)")]
		public string diaDiem
		{
			get
			{
				return this._diaDiem;
			}
			set
			{
				if ((this._diaDiem != value))
				{
					this.OndiaDiemChanging(value);
					this.SendPropertyChanging();
					this._diaDiem = value;
					this.SendPropertyChanged("diaDiem");
					this.OndiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiGianKetThuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> thoiGianKetThuc
		{
			get
			{
				return this._thoiGianKetThuc;
			}
			set
			{
				if ((this._thoiGianKetThuc != value))
				{
					this.OnthoiGianKetThucChanging(value);
					this.SendPropertyChanging();
					this._thoiGianKetThuc = value;
					this.SendPropertyChanged("thoiGianKetThuc");
					this.OnthoiGianKetThucChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
